require("somya.core.options")
require("somya.core.filetypes")
require("somya.core.keymaps")
require("somya.core.autocmds")
require("somya.core.abbreviations")
require("somya.cheatsheet")
require("somya.version") -- registers :SDVersion (version + build id for reports)
