return {
	"stevearc/conform.nvim",
	event = { "BufReadPre", "BufNewFile" },
	config = function()
		local conform = require("conform")

		conform.setup({
			formatters_by_ft = {
				css = { "prettier" },
				html = { "prettier" },
				json = { "prettier" },
				yaml = { "prettier" },
				markdown = { "prettier" },
				systemverilog = { "verible" },
				verilog = { "verible" },
				lua = { "stylua" },
				python = { "isort", "black" },
			},
			formatters = {
				verible = (function()
					-- Prefer a per-project flagfile (`.verible_format`, generated by
					-- `verible-init`) found by walking up from the file's directory.
					-- With no project config, fall back to verible's own defaults.
					-- `--failsafe_success=false` (after the flagfile, so it wins) makes
					-- a syntax error exit nonzero: verible's default is to exit 0 and
					-- echo the input UNCHANGED, which conform sees as a successful
					-- format with no diff — i.e. <leader>vf silently does nothing on a
					-- file that doesn't parse. This way conform surfaces verible's
					-- stderr (with the error location) as a notification instead.
					local function base_args(ctx, extra)
						local args = {}
						local found = vim.fs.find(".verible_format", { upward = true, path = ctx.dirname })[1]
						if found then
							table.insert(args, "--flagfile=" .. found)
						end
						table.insert(args, "--failsafe_success=false")
						vim.list_extend(args, extra or {})
						table.insert(args, "-")
						return args
					end
					return {
						command = "verible-verilog-format",
						stdin = true,
						args = function(_, ctx)
							return base_args(ctx)
						end,
						-- Visual-selection formatting via verible's native --lines,
						-- so only the selected lines are touched.
						range_args = function(_, ctx)
							return base_args(ctx, {
								"--lines",
								("%d-%d"):format(ctx.range.start[1], ctx.range["end"][1]),
							})
						end,
					}
				end)(),
			},
			--     format_on_save = {
			--       lsp_fallback = true,
			--       async = false,
			--       timeout_ms = 1000,
			--     },
		})

		-- General format keybinding (works with visual selection or whole file).
		-- Picks the formatter for the current filetype (prettier/stylua/black/…,
		-- verible for SV), falling back to the LSP formatter if none is configured.
		-- Pairs with <leader>vf below, which always forces Verible. (Lives under the
		-- <leader>v "LSP / Code" group — uppercase F to sit beside lowercase vf.)
		vim.keymap.set({ "n", "v" }, "<leader>vF", function()
			conform.format({
				lsp_fallback = true,
				async = false,
				timeout_ms = 1000,
			})
		end, { desc = "Format file/range (auto formatter, LSP fallback)" })

		-- Dedicated Verible format and align keybinding
		vim.keymap.set({ "n", "v" }, "<leader>vf", function()
			conform.format({
				formatters = { "verible" },
				lsp_fallback = false,
				async = false,
				timeout_ms = 1000,
			})
		end, { desc = "Format and align with Verible" })
	end,
}
